### ISSUE TITLE
Unable to import nltk (model branch)

### ISSUE THREAD

**Issue by rivaborbely** [nltk/nltk.github.com#4]
I get an ImportError on attempting to import nltk:  "ImportError: No module named sparsefuncs"

I am using the model branch of NLTK (installed today with "pip install https://github.com/nltk/nltk/tarball/model".)

Traceback (most recent call last):
  File "../MyFile.py", line 3, in <module>
    import nltk
  File "/usr/local/lib/python2.7/dist-packages/nltk/**init**.py", line 117, in <module>
    from nltk.align import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/align/**init**.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "/usr/local/lib/python2.7/dist-packages/nltk/align/ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/**init**.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/**init**.py", line 62, in <module>
    from nltk.corpus.reader.chunked import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/chunked.py", line 21, in <module>
    from nltk.chunk import tagstr2tree
  File "/usr/local/lib/python2.7/dist-packages/nltk/chunk/**init**.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/usr/local/lib/python2.7/dist-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/usr/local/lib/python2.7/dist-packages/nltk/parse/**init**.py", line 79, in <module>
    from nltk.parse.transitionparser import TransitionParser
  File "/usr/local/lib/python2.7/dist-packages/nltk/parse/transitionparser.py", line 17, in <module>
    from sklearn.datasets import load_svmlight_file
  File "/usr/lib/python2.7/dist-packages/sklearn/datasets/**init**.py", line 23, in <module>
    from .twenty_newsgroups import fetch_20newsgroups
  File "/usr/lib/python2.7/dist-packages/sklearn/datasets/twenty_newsgroups.py", line 53, in <module>
    from ..feature_extraction.text import CountVectorizer
  File "/usr/lib/python2.7/dist-packages/sklearn/feature_extraction/**init**.py", line 10, in <module>
    from . import text
  File "/usr/lib/python2.7/dist-packages/sklearn/feature_extraction/text.py", line 29, in <module>
    from ..preprocessing import normalize
  File "/usr/lib/python2.7/dist-packages/sklearn/preprocessing/**init**.py", line 6, in <module>
    from .data import Binarizer
  File "/usr/lib/python2.7/dist-packages/sklearn/preprocessing/data.py", line 20, in <module>
    from ..utils.sparsefuncs import inplace_csr_row_normalize_l1
ImportError: No module named sparsefuncs

In case they're relevant, I did get two warnings on my install of NLTK:
warning: no files found matching 'Makefile' under directory '_.txt'
warning: no previously-included files matching '_~' found anywhere in distribution

**Comment by rivaborbely** [comment]
Fixed by updating scikit-learn.

**Comment by MaxValue** [comment]
You can close the issue by clicking "Close Issue".
